Repository KoladTech/david-bukola-foundation, pull requests merged in 2024-12, with the labels that each got.

#20 Meet our team feature update
  public/Head-Consultant-image.png
  src/app/about/page.js
  src/components/MeetOurTeam.js
Labels: enhancement

#22 docs: Create VERSION
  VERSION
Labels: documentation

#21 Create deploy.yml
  .github/workflows/deploy.yml
Labels: enhancement

#24 Test GitHub action workflow
  src/app/layout.js
  src/components/HeroSection.js
Labels: enhancement

#26 docs: Create VERSION
  VERSION
Labels: documentation

#25 Create GitHub actions workflow
  .github/workflows/deploy.yml
Labels: enhancement

#27 Project page backend
  public/borehole-project-image.jpg
  public/projects-herosection-image.jpg
  src/app/projects/page.js
  src/firebase/projectPage.js
Labels: enhancement

#29 Project page fix
  public/dbf-hands-collaboration.png
  public/meet-the-team-1.png
  public/meet-the-team-2.png
  public/meet-the-team-3.png
  public/meet-the-team-4.png
  public/project-page-image.png
  public/project-page-main-image.png
  src/app/projects/page.js
  src/constants.js
Labels: minor-fix

#30 Achievements data
  .gitignore
  public/achievements-1-image1.jpg
  public/achievements-1-image2.jpg
  public/achievements-2-image1.jpg
  public/achievements-2-image2.png
  public/achievements-4-image1.jpg
  public/achievements-4-image2.jpg
  src/app/achievements/SchoolsList.js
  src/app/achievements/TruncatedText.js
  src/app/achievements/page.js
  src/components/HeroSection.js
  src/firebase/firebaseConfig.js
  src/firebase/testFirebase.js
Labels: enhancement

#37 re-add current version
  VERSION
Labels: bug

#38 UI improvements
  src/app/achievements/page.js
  src/app/layout.js
Labels: minor-fix

#42 fix(style/bug): fixes breakpoint & alignments
  src/app/achievements/page.js
  src/app/layout.js
  src/app/projects/page.js
  src/app/testimonials/page.js
  src/components/ContentCard.js
  src/components/MeetOurTeam.js
  src/components/TestimonyCards.js
  src/firebase/fetchFirebaseData.js
  src/firebase/projectPage.js
Labels: minor-fix

#41 Update read me branch
  .github/workflows/deploy.yml
  README.md
  VERSION
  src/app/layout.js
Labels: documentation

#43 (fix): fix minor issues with achievements page
  public/images/achievements-4-image2.jpg
  src/components/HeroSection.js
Labels: minor-fix

#45 Merge for production build
  README.md
  public/images/achievements-4-image2.jpg
  public/images/boy-looking-up-image.jpg
  public/images/boy-writing-image.jpg
  public/images/coding-image.jpg
  src/app/achievements/page.js
  src/app/layout.js
  src/app/loading.js
  src/app/page.js
  src/app/projects/page.js
  src/app/testimonials/page.js
  src/components/ContentCard.js
  src/components/HeroSection.js
  src/components/MeetOurTeam.js
  src/components/TestimonyCards.js
  src/firebase/fetchFirebaseData.js
  src/firebase/projectPage.js
Labels: enhancement

#46 Checklist fixes branch
  src/app/globals.css
  src/app/layout.js
  src/app/testimonials/page.js
  src/components/ShareTestimony.js
  src/components/TestimonyCards.js
  tailwind.config.js
Labels: enhancement

#47 General bug fixes
  src/app/achievements/page.js
  src/app/layout.js
  src/app/page.js
  src/app/projects/page.js
  src/components/Achievement.js
  src/components/AchievementWidgets.js
  src/components/HeroSection.js
  src/context/ApiStatsContext.js
Labels: enhancement

#48 Careers page
  public/images/achievements-5-image1.jpg
  public/images/careers_page_hero_section_image.png
  public/images/get_involved_careers_image.png
  public/images/get_involved_events_image.png
  public/images/get_involved_hero_section_image.png
  public/images/get_involved_volunteer_image.png
  src/app/careers/[jobId]/page.js
  src/app/careers/page.js
  src/app/events/page.js
  src/app/get-involved/page.js
  src/app/volunteer/page.js
Labels: enhancement

#49 (fix):Fix header responsiveness and GetInvolved links
  src/app/layout.js
  src/components/GetInvolved.js
Labels: bug

#54 Events page
  public/images/christmas_giveaway_image.png
  public/images/events_hero_section.jpg
  public/images/food_drive_poster.png
  src/app/achievements/page.js
  src/app/events/page.js
  src/app/projects/page.js
  src/app/testimonials/page.js
  src/components/HeroSection.js
  src/components/TestimonyCards.js
  src/firebase/fetchFirebaseData.js
  src/lib/utils.js
Labels: enhancement

#55 General tasks
  src/app/achievements/page.js
  src/app/careers/[slug]/page.js
  src/app/careers/page.js
  src/app/events/page.js
  src/app/page.js
  src/components/HeroSection.js
  src/firebase/firebaseConfig.js
Labels: enhancement, refactor

#56 Checklist branch
  public/images/dbf-achievement-page-image1.jpg
  public/images/dbf-footer-image.jpg
  public/images/dbf-home-achievements-image.jpg
  public/images/dbf-home-page-image.jpg
  src/app/achievements/page.js
  src/app/api/sendEmail/route.js
  src/app/layout.js
  src/app/page.js
  src/app/testimonials/page.js
  src/components/ContentCard.js
  src/components/HeroSection.js
  src/components/PictureCard.js
  src/components/ProjectCard.js
  src/components/ShareTestimony.js
  src/components/TestimonyCards.js
Labels: refactor

#58 (fix): add statsLoading prop to achievments widget
  src/app/page.js
Labels: bug

#57 new Build for production
  public/images/christmas_giveaway_image.png
  public/images/dbf-achievement-page-image1.jpg
  public/images/dbf-footer-image.jpg
  public/images/dbf-home-achievements-image.jpg
  public/images/dbf-home-page-image.jpg
  public/images/events_hero_section.jpg
  public/images/food_drive_poster.png
  src/app/achievements/page.js
  src/app/api/sendEmail/route.js
  src/app/careers/[slug]/page.js
  src/app/careers/page.js
  src/app/events/page.js
  src/app/layout.js
  src/app/page.js
  src/app/projects/page.js
  src/app/testimonials/page.js
  src/components/ContentCard.js
  src/components/HeroSection.js
  src/components/PictureCard.js
  src/components/ProjectCard.js
  src/components/ShareTestimony.js
  src/components/TestimonyCards.js
  src/firebase/fetchFirebaseData.js
  src/firebase/firebaseConfig.js
  src/lib/utils.js
Labels: Build
