Repository KoladTech/david-bukola-foundation, pull requests merged in 2024-11, with the labels that each got.

#9 Home page
  package-lock.json
  package.json
  public/achievements-image.png
  public/donate-now-image.png
  public/foundation-name-and-motto-image.png
  public/get-involved-image.png
  public/join-us-image.png
  public/meet-the-team-1.png
  public/meet-the-team-2.png
  public/meet-the-team-3.png
  public/meet-the-team-4.png
  public/projects-image.png
  src/app/globals.css
  src/app/layout.js
  src/app/page.js
  src/components/AboutUs.js
  src/components/Achievement.js
  src/components/AchievementWidgets.js
  src/components/ContentCard.js
  src/components/DonationWidget.js
  src/components/FAQ.js
  src/components/HeroSection.js
  src/components/PictureCard.js
  src/components/TestimonyCards.js
Labels: enhancement

#10 About us
  public/donate-image.jpg
  public/join-image.jpg
  public/main_about_us.jpg
  public/person placeholder.png
  src/app/about/page.js
  src/app/achievements/page.js
  src/app/donate/page.js
  src/app/join/page.js
  src/app/layout.js
  src/app/page.js
  src/app/projects/page.js
  src/components/GetInvolved.js
  src/components/GetInvolvedOption.js
  src/components/MeetOurTeam.js
  src/components/UnderConstruction.js
Labels: enhancement

#11 Fix social media links and justify about us text
  src/app/about/page.js
  src/app/layout.js
Labels: bug

#12 fix minor design and link bugs
  src/app/about/page.js
  src/app/page.js
  src/components/AchievementWidgets.js
  src/components/FAQ.js
Labels: bug

#15 Fix footer home about us
  src/app/about/page.js
  src/app/globals.css
  src/app/layout.js
  src/components/AboutUs.js
Labels: minor-fix

#16 Merge project page
  public/project-page-image1.png
  public/project-page-image2.png
  public/project-page-main-image.png
  src/app/about/page.js
  src/app/layout.js
  src/app/page.js
  src/app/projects/page.js
  src/components/ContentCard.js
  src/components/GetInvolved.js
  src/components/HeroSection.js
  src/components/MeetOurTeam.js
  src/components/PictureCard.js
Labels: enhancement, help wanted, minor-fix

#17 Achievements page
  public/achievements-hero-image.jpg
  public/achievements-image-1.jpg
  public/achievements-image-2.jpg
  src/app/achievements/page.js
  src/app/projects/page.js
  src/components/HeroSection.js
Labels: enhancement

#18 setup firebase and test creating documents
  package-lock.json
  package.json
  src/firebase/firebaseConfig.js
  src/firebase/testFirebase.js
Labels: enhancement
