Repository KoladTech/david-bukola-foundation, pull requests merged in 2025-01, with the labels that each got.

#59 Donate page
  package-lock.json
  package.json
  src/app/api/sendDonationEmail/route.js
  src/app/api/sendEmail/route.js
  src/app/donate/page.js
  src/app/globals.css
  src/app/page.js
  src/components/HeroSection.js
  src/components/ShareTestimony.js
  src/components/ui/checkbox.jsx
  src/components/ui/label.jsx
  src/context/ApiBankDetailsContext.js
  src/firebase/createUser.js
  src/firebase/fetchFirebaseData.js
  src/lib/emailVerification.js
  src/lib/thankYouMessage.js
Labels: enhancement

#60 Volunteer page
  package-lock.json
  package.json
  src/app/achievements/page.js
  src/app/api/newVolunteerEmail/route.js
  src/app/api/sendMail/route.js
  src/app/events/EventCard.js
  src/app/events/VolunteerForm.js
  src/app/events/page.js
  src/app/volunteer/page.js
  src/components/ImageModal.js
  src/components/ui/collapsible.jsx
  src/components/ui/input.jsx
  src/components/ui/label.jsx
  src/components/ui/textarea.jsx
  src/lib/utils.js
Labels: enhancement, minor-fix

#61 (minor): consolidate email routes
  src/app/api/newVolunteerEmail/route.js
  src/app/api/sendDonationEmail/route.js
  src/app/api/sendEmail/route.js
  src/app/api/sendMail/route.js
  src/app/donate/page.js
  src/app/events/VolunteerForm.js
  src/app/events/page.js
  src/app/volunteer/page.js
  src/firebase/createUser.js
Labels: enhancement, refactor

#62 Merge-into-production
  package-lock.json
  package.json
  public/images/donate-image.jpg
  src/app/achievements/page.js
  src/app/api/sendEmail/route.js
  src/app/api/sendMail/route.js
  src/app/donate/page.js
  src/app/events/EventCard.js
  src/app/events/VolunteerForm.js
  src/app/events/page.js
  src/app/globals.css
  src/app/page.js
  src/app/projects/page.js
  src/app/volunteer/page.js
  src/components/HeroSection.js
  src/components/ImageModal.js
  src/components/MeetOurTeam.js
  src/components/ShareTestimony.js
  src/components/ui/checkbox.jsx
  src/components/ui/collapsible.jsx
  src/components/ui/input.jsx
  src/components/ui/label.jsx
  src/components/ui/textarea.jsx
  src/constants.js
  src/context/ApiBankDetailsContext.js
  src/firebase/createUser.js
  src/firebase/fetchFirebaseData.js
  src/firebase/projectPage.js
  src/lib/emailVerification.js
  src/lib/thankYouMessage.js
  src/lib/utils.js
Labels: enhancement, minor-fix, refactor

#64 cleanUp(all pages): add clean up to codebase
  src/app/about/page.js
  src/app/achievements/SchoolsList.js
  src/app/achievements/TruncatedText.js
  src/app/achievements/page.js
  src/app/api/sendMail/route.js
  src/app/careers/[slug]/page.js
  src/app/donate/page.js
  src/app/events/EventCard.js
  src/app/events/VolunteerForm.js
  src/app/events/page.js
  src/app/get-involved/page.js
  src/app/join/page.js
  src/app/layout.js
  src/app/loading.js
  src/app/page.js
  src/app/projects/page.js
  src/app/testimonials/page.js
  src/app/volunteer/page.js
  src/components/Achievement.js
  src/components/ContentCard.js
  src/components/ImageModal.js
  src/components/ShareTestimony.js
  src/constants.js
  src/context/ApiBankDetailsContext.js
  src/lib/utils.js
Labels: refactor

#65 General tasks
  src/app/about/page.js
  src/app/achievements/page.js
  src/app/api/sendMail/route.js
  src/app/careers/[slug]/page.js
  src/app/careers/page.js
  src/app/donate/page.js
  src/app/events/VolunteerForm.js
  src/app/events/page.js
  src/app/get-involved/page.js
  src/app/globals.css
  src/app/layout.js
  src/app/page.js
  src/app/projects/page.js
  src/app/volunteer/page.js
  src/components/HeroSection.js
  src/lib/utils.js
Labels: enhancement, refactor

#67 (minor): fixed bugs
  src/app/events/page.js
  src/app/get-involved/page.js
  src/app/layout.js
  src/app/volunteer/page.js
  src/components/HeroSection.js
Labels: minor-fix

#69 feature(donate): add search functionality
  src/app/api/sendMail/route.js
  src/app/donate/OtherWaysToGive.js
  src/app/donate/page.js
  src/app/donate/previousCountryCode.js
  src/app/testimonials/TestimonyForm.js
  src/firebase/createUser.js
Labels: enhancement, minor-fix

#71 Production branch
  Dockerfile
  src/app/about/page.js
  src/app/get-involved/page.js
  src/app/volunteer/page.js
Labels: minor-fix

#72 New checklist fixes
  package-lock.json
  package.json
  src/app/api/sendMail/route.js
  src/app/donate/page.js
  src/app/globals.css
  src/app/layout.js
  src/app/page.js
  src/app/projects/page.js
  src/app/testimonials/TestimonyForm.js
  src/app/testimonials/page.js
  src/components/GetInvolved.js
  src/components/GetInvolvedOption.js
  src/components/HeroSection.js
  src/components/MeetOurTeam.js
  src/components/NewsLetter.js
  src/components/PictureCard.js
  src/components/ProjectCard.js
  src/components/TestimonyCards.js
  src/components/VideoPlayer.js
  src/components/ui/slider.jsx
  src/components/ui/toast.jsx
  src/components/ui/toaster.jsx
  src/firebase/createUser.js
  src/hooks/use-toast.js
Labels: minor-fix

#73 Chores and fixes
  next.config.mjs
  package-lock.json
  package.json
  src/app/achievements/page.js
  src/app/careers/page.js
  src/app/donate/page.js
  src/app/events/EventCard.js
  src/app/events/page.js
  src/app/get-involved/page.js
  src/app/globals.css
  src/app/layout.js
  src/app/loading.js
  src/app/page.js
  src/app/projects/page.js
  src/components/HeroSection.js
  src/components/ImageModal.js
  src/components/ui/tabs.jsx
Labels: enhancement

#74 New Merge for Build(Minor)
  next.config.mjs
  package-lock.json
  package.json
  src/app/achievements/page.js
  src/app/api/sendMail/route.js
  src/app/careers/page.js
  src/app/donate/page.js
  src/app/events/EventCard.js
  src/app/events/page.js
  src/app/get-involved/page.js
  src/app/globals.css
  src/app/layout.js
  src/app/loading.js
  src/app/page.js
  src/app/projects/page.js
  src/app/testimonials/TestimonyForm.js
  src/app/testimonials/page.js
  src/components/GetInvolved.js
  src/components/GetInvolvedOption.js
  src/components/HeroSection.js
  src/components/ImageModal.js
  src/components/MeetOurTeam.js
  src/components/NewsLetter.js
  src/components/PictureCard.js
  src/components/ProjectCard.js
  src/components/TestimonyCards.js
  src/components/VideoPlayer.js
  src/components/ui/slider.jsx
  src/components/ui/tabs.jsx
  src/components/ui/toast.jsx
  src/components/ui/toaster.jsx
  src/firebase/createUser.js
  src/hooks/use-toast.js
Labels: Build

#75 feat(admin-sdk): add firebase admin sdk to project
  package-lock.json
  package.json
  src/app/about/page.js
  src/app/achievements/page.js
  src/app/careers/[slug]/page.js
  src/app/careers/page.js
  src/app/donate/page.js
  src/app/events/EventCard.js
  src/app/events/VolunteerForm.js
  src/app/events/page.js
  src/app/get-involved/page.js
  src/app/layout.js
  src/app/loading.js
  src/app/page.js
  src/app/projects/page.js
  src/app/testimonials/TestimonyForm.js
  src/app/testimonials/page.js
  src/app/volunteer/page.js
  src/components/Achievement.js
  src/components/GetInvolved.js
  src/components/MeetOurTeam.js
  src/components/NewsLetter.js
  src/components/ProjectCard.js
  src/components/TestimonyCards.js
  src/context/ApiStatsContext.js
  src/lib/constants.js
  src/lib/firebase/createUser.js
  src/lib/firebase/fetchFirebaseData.js
  src/lib/firebase/firebaseAdmin.js
  src/lib/firebase/firebaseConfig.js
  src/lib/firebase/handleFormSubmission.js
  src/lib/firebase/testFirebase.js
Labels: enhancement
